# Generated by Django 5.1.7 on 2025-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('project', 'Project'), ('modification', 'Modification'), ('drawing', 'Drawing')], max_length=20)),
                ('proposed_title', models.CharField(max_length=200)),
                ('request_date', models.DateField()),
                ('user_requirement_specification', models.TextField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('purpose', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=200)),
                ('requested_by', models.CharField(max_length=100)),
            ],
        ),
    ]
