# Generated by Django 5.1.7 on 2025-04-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('new', 'New Machine'), ('modification', 'Modification'), ('repair', 'Repair')], default='new', max_length=50)),
                ('proposed_title', models.CharField(max_length=100)),
                ('request_date', models.DateField()),
                ('purpose', models.TextField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked', 'Checked'), ('assigned', 'Assigned')], default='pending', max_length=10)),
                ('supervisor_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_approve_request', 'Can approve request'), ('can_reject_request', 'Can reject request'), ('can_review_supervisor', 'Can review supervisor'), ('can_assign_engineer', 'Can assign Engineer')],
            },
        ),
        migrations.AlterModelOptions(
            name='requestform',
            options={
                'permissions': [
                    ('can_approve_request', 'Can approve request'),
                    ('can_reject_request', 'Can reject request'),
                    ('can_review_supervisor', 'Can review supervisor'),
                    ('can_assign_engineer', 'Can assign Engineer'),
                ],
            },
        ),
    ]
