# Generated by Django 5.1.7 on 2025-04-10 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestform',
            options={'permissions': [('can_approve_request', 'Can approve request'), ('can_reject_request', 'Can reject request'), ('can_verify_request', 'Can verify request'), ('can_assign_engineer', 'Can assign Engineer')]},
        ),
        migrations.RenameField(
            model_name='requestform',
            old_name='assigned_to',
            new_name='assigned_engineer',
        ),
        migrations.AddField(
            model_name='requestform',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestform',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked', 'Checked'), ('assigned', 'Assigned')], default='pending', max_length=10),
        ),
    ]
