# Generated by Django 5.1.7 on 2025-04-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='request_type',
            field=models.CharField(choices=[('project', 'Project'), ('modification', 'Modification'), ('drawing', 'Drawing')], default='new', max_length=50),
        ),
    ]
