# Generated by Django 5.1.7 on 2025-04-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_requestform_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('manager_approved', 'Manager Approved'), ('supervisor_approved', 'Supervisor Approved'), ('engineer_assigned', 'Engineer Assigned')], default='created', max_length=20),
        ),
    ]
