# Generated by Django 5.1.7 on 2025-04-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_requestform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestform',
            options={'permissions': [('can_approve_request', 'Can approve request'), ('can_reject_request', 'Can reject request'), ('can_review_supervisor', 'Can review supervisor'), ('can_assign_engineer', 'Can assign Engineer')]},
        ),
        migrations.AddField(
            model_name='requestform',
            name='supervisor_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
